# Generated by Django 6.0 on 2026-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_credits', models.PositiveIntegerField(default=0)),
                ('lifetime_debits', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Credit Accounts',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('credits', models.PositiveIntegerField(choices=[(5000, '5,000 credits'), (10000, '10,000 credits'), (50000, '50,000 credits'), (100000, '100,000 credits'), (500000, '500,000 credits'), (1000000, '1,000,000 credits')])),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Credit Vouchers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('alipay', 'Alipay'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('provider_trade_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
