# Generated by Django 6.0 on 2026-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditvoucher',
            name='credits',
            field=models.PositiveIntegerField(choices=[(1000, '1,000 credits'), (5000, '5,000 credits'), (10000, '10,000 credits'), (50000, '50,000 credits'), (100000, '100,000 credits'), (500000, '500,000 credits'), (1000000, '1,000,000 credits')]),
        ),
    ]
