# Generated by Django 6.0 on 2026-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='audio_intro',
            field=models.FileField(null=True, upload_to='store/audio/host-intro'),
        ),
        migrations.AddField(
            model_name='host',
            name='cover',
            field=models.ImageField(null=True, upload_to='store/image/host-back'),
        ),
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='portrait',
            field=models.ImageField(null=True, upload_to='store/image/host-avatar'),
        ),
    ]
