# Generated by Django 6.0 on 2026-01-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_host_audio_intro_host_cover_host_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='audio_intro',
            field=models.FileField(blank=True, null=True, upload_to='store/audio/host-intro'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='store/image/host-back'),
        ),
        migrations.AlterField(
            model_name='host',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='store/image/host-avatar'),
        ),
    ]
