# Generated by Django 6.0.1 on 2026-02-14 09:59

import django.db.models.deletion
import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_host_audio_intro_alter_host_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='subtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='store.subtitle'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to=store.utils.video_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='original',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
