# Generated by Django 6.0.1 on 2026-02-17 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_expression_subtitle_alter_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='store.host')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='store.playlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='store.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'order'), ('playlist', 'product')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='products',
            field=models.ManyToManyField(related_name='playlists', through='store.PlaylistItem', to='store.product'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('host', 'slug')},
        ),
    ]
