# Generated by Django 6.0.1 on 2026-02-17 06:48

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_playlist_playlistitem_playlist_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='short_uuid',
            field=models.CharField(default=store.utils.short_uuid, editable=False, max_length=22, unique=True),
        ),
    ]
