# Generated by Django 6.0.1 on 2026-02-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_playlist_short_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('cover', models.ImageField(blank=True, upload_to='store/image/course-cover')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, upload_to='store/image/list-cover'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='store.course'),
        ),
    ]
