# Generated by Django 6.0.1 on 2026-02-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_course_alter_playlist_options_playlist_cover_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='store.host'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('host', 'slug')},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='host',
        ),
    ]
