# Generated by Django 6.0.1 on 2026-02-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_playlist_unique_together_course_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='store.host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='store.host'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('host', 'slug')},
        ),
    ]
