# Generated by Django 6.0.1 on 2026-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_playlist_host_alter_course_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
