# Generated by Django 6.0.1 on 2026-02-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_subtitle_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated_at']},
        ),
    ]
