# Generated by Django 6.0.1 on 2026-04-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='store.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
