# Generated by Django 6.0.1 on 2026-04-20 10:50

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_host_language_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='audio',
            field=models.FileField(blank=True, upload_to=store.utils.subtitle_audio_upload_to),
        ),
    ]
