# Generated by Django 6.0.1 on 2026-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone, e.g., 'Asia/Tokyo'", max_length=50),
        ),
    ]
