# Generated by Django 6.0 on 2026-01-04 10:28

import django.db.models.deletion
import interact.utils.mediauploadto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('is_enhancement', models.BooleanField(default=False)),
                ('enhanced_content', models.TextField(blank=True)),
                ('is_voice', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to=interact.utils.mediauploadto.chat_audio_upload_to)),
                ('audio_seconds', models.IntegerField(blank=True, default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, help_text='Cached sum of ModelUsage costs (derived)', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_key', models.IntegerField(editable=False)),
                ('visible', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('latest_chat', models.TextField(blank=True, max_length=255)),
                ('cost', models.DecimalField(decimal_places=6, default=0, help_text='Cached sum of ModelUsage costs (derived)', max_digits=12)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='store.host')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='store.product')),
                ('summary_upto_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='interact.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'host', 'product_key')},
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interact.chatsession'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interact.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Collection Items',
                'ordering': ['-created_at'],
                'unique_together': {('collection', 'product')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(related_name='collections', through='interact.CollectionItem', to='store.product'),
        ),
        migrations.CreateModel(
            name='ModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.CharField(db_index=True, editable=False, max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=6, editable=False, max_digits=12)),
                ('units', models.DecimalField(decimal_places=3, help_text='1K-tokens, seconds, characters', max_digits=12)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=12)),
                ('chat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_costs', to='ai.modelprovider')),
                ('message', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_costs', to='interact.chatmessage')),
                ('session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='usage_costs', to='interact.chatsession')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='usage_costs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Model Usages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebitLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledgers', to=settings.AUTH_USER_MODEL)),
                ('usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interact.modelusage')),
            ],
            options={
                'verbose_name_plural': 'Debit Ledgers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'title')},
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='store.host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Followings',
                'ordering': ['id'],
                'unique_together': {('user', 'host')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Likes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='modelusage',
            index=models.Index(fields=['step'], name='interact_mo_step_cf354e_idx'),
        ),
        migrations.AddIndex(
            model_name='modelusage',
            index=models.Index(fields=['created_at'], name='interact_mo_created_5f0833_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('user', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='userview',
            unique_together={('user', 'product')},
        ),
    ]
