# Generated by Django 6.0.1 on 2026-01-16 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
        ('store', '0003_alter_host_audio_intro_alter_host_cover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusage',
            name='session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_costs', to='interact.chatsession'),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('terminated', 'Terminated')], default='active', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='store.host')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Call Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='modelusage',
            name='call_session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_costs', to='interact.callsession'),
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('text', models.TextField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='interact.callsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
