# Generated by Django 6.0.1 on 2026-01-20 02:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_alter_modelusage_session_callsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
