# Generated by Django 6.0.1 on 2026-01-20 06:23

import django.db.models.deletion
import interact.utils.mediauploadto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0003_callsession_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltranscript',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='product',
        ),
        migrations.RemoveField(
            model_name='callsession',
            name='user',
        ),
        migrations.AddField(
            model_name='callsession',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='interact.chatsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=interact.utils.mediauploadto.chat_audio_upload_to),
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='audio_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
