# Generated by Django 6.0.1 on 2026-01-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0004_rename_text_calltranscript_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='call_session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='interact.callsession'),
        ),
        migrations.DeleteModel(
            name='CallTranscript',
        ),
    ]
