# Generated by Django 6.0.1 on 2026-02-17 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0005_chatmessage_call_session_delete_calltranscript'),
        ('store', '0005_playlist_playlistitem_playlist_products_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debitledger',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SavedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_playlists', to='store.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
