# Generated by Django 6.0.1 on 2026-02-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0006_alter_chatsession_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedplaylist',
            options={'ordering': ['-saved_at']},
        ),
        migrations.RenameField(
            model_name='savedplaylist',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.RemoveField(
            model_name='savedplaylist',
            name='updated_at',
        ),
    ]
