# Generated by Django 6.0.1 on 2026-02-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0008_savedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='short_uuid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
