# Generated by Django 6.0.1 on 2026-02-20 04:50

from django.db import migrations
from store.utils import short_uuid


def generate_short_uuid(apps, schema_editor):
    Collection = apps.get_model('interact', 'Collection')

    for obj in Collection.objects.filter(short_uuid__isnull=True):
        obj.short_uuid = short_uuid()
        obj.save(update_fields=['short_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0009_collection_short_uuid_alter_collection_slug'),
    ]

    operations = [
        migrations.RunPython(generate_short_uuid),
    ]
