# Generated by Django 6.0.1 on 2026-02-20 05:08

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0010_auto_20260220_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='short_uuid',
            field=models.CharField(default=store.utils.short_uuid, editable=False, max_length=22, unique=True),
        ),
    ]
