# Generated by Django 6.0.1 on 2026-02-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0011_alter_collection_short_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assistant_audio_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='call_audio_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='credits_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_audio_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debitledger',
            name='usage',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='interact.modelusage'),
            preserve_default=False,
        ),
    ]
