# Generated by Django 6.0.1 on 2026-04-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0012_chatsession_assistant_audio_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('user_intents', models.JSONField(blank=True, default=list)),
                ('vocabulary', models.JSONField(blank=True, default=list)),
                ('grammar_issues', models.JSONField(blank=True, default=list)),
                ('speaking_style', models.JSONField(blank=True, default=dict)),
                ('corrections_given', models.JSONField(blank=True, default=list)),
                ('key_moments', models.JSONField(blank=True, default=list)),
                ('json_version', models.IntegerField(default=1)),
                ('message_count', models.IntegerField(default=0)),
                ('user_audio_duration', models.IntegerField(default=0)),
                ('host_audio_duration', models.IntegerField(default=0)),
                ('call_count', models.IntegerField(default=0)),
                ('call_duration', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interact.chatsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
