# Generated by Django 6.0.1 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0013_sessionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'STT'), ('call', 'Call')], default='text', max_length=10),
        ),
    ]
