# Generated by Django 6.0.1 on 2026-04-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0014_chatmessage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsummary',
            name='corrections_given',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='grammar_issues',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='key_moments',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='key_topics',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='user_intents',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='vocabulary',
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='teaching_strategy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sessionsummary',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessionsummary', to='interact.chatsession'),
        ),
        migrations.AlterField(
            model_name='sessionsummary',
            name='summary',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('user_version', models.TextField()),
                ('improved_version', models.TextField()),
                ('vocabulary', models.JSONField(blank=True, default=list)),
                ('phrase', models.JSONField(blank=True, decoder=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interact.chatsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
