# Generated by Django 6.0.1 on 2026-04-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0015_remove_sessionsummary_corrections_given_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionevent',
            old_name='improved_version',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sessionevent',
            old_name='notes',
            new_name='topics',
        ),
        migrations.RenameField(
            model_name='sessionsummary',
            old_name='progress',
            new_name='strategy',
        ),
        migrations.RenameField(
            model_name='sessionsummary',
            old_name='speaking_style',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='happened_at',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='user_version',
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='teaching_strategy',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='interact.sessionevent'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MessageRewrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('vocabulary', models.JSONField(blank=True, default=list)),
                ('phrase', models.JSONField(blank=True, default=list)),
                ('note', models.JSONField(blank=True, default=list)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='interact.chatmessage')),
            ],
        ),
    ]
