# Generated by Django 6.0.1 on 2026-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0016_rename_improved_version_sessionevent_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
