# Generated by Django 6.0.1 on 2026-04-07 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0017_sessionevent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerewrite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagerewrite',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning', to='interact.chatmessage'),
        ),
    ]
