# Generated by Django 6.0.1 on 2026-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0018_messagerewrite_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('fr', 'French')], default='en', max_length=10),
            preserve_default=False,
        ),
    ]
