# Generated by Django 6.0.1 on 2026-04-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0019_chatsession_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callsession',
            options={'ordering': ['-started_at'], 'verbose_name_plural': 'Chat Call Sessions'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Chat Session Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Collections'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Collection Items'},
        ),
        migrations.AlterModelOptions(
            name='debitledger',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'User Debit Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id'], 'verbose_name_plural': 'User Followings'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Likes'},
        ),
        migrations.AlterModelOptions(
            name='modelusage',
            options={'ordering': ['id'], 'verbose_name_plural': 'Chat Model Usages'},
        ),
        migrations.AlterModelOptions(
            name='savedcourse',
            options={'ordering': ['-saved_at'], 'verbose_name_plural': 'User Saved Course'},
        ),
        migrations.AlterModelOptions(
            name='savedplaylist',
            options={'ordering': ['-saved_at'], 'verbose_name_plural': 'User Saved Playlist'},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Searches'},
        ),
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'verbose_name_plural': 'Chat Session Events'},
        ),
        migrations.AlterModelOptions(
            name='sessionsummary',
            options={'verbose_name_plural': 'Chat Session Summary'},
        ),
        migrations.AlterModelOptions(
            name='userview',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'User Histories'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('call', 'Call')], default='text', max_length=10),
        ),
    ]
