# Generated by Django 6.0.1 on 2026-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0020_alter_callsession_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsummary',
            name='call_count',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='call_duration',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='host_audio_duration',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='json_version',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='style',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='user_audio_duration',
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
