# Generated by Django 6.0.1 on 2026-04-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0021_remove_sessionsummary_call_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='summary_upto_message',
        ),
    ]
