# Generated by Django 6.0.1 on 2026-04-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0022_remove_chatsession_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusage',
            name='call_session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_costs', to='interact.callsession'),
        ),
        migrations.AlterField(
            model_name='modelusage',
            name='message',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_costs', to='interact.chatmessage'),
        ),
        migrations.AlterField(
            model_name='modelusage',
            name='session',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_costs', to='interact.chatsession'),
        ),
    ]
