# Generated by Django 6.0.1 on 2026-04-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0023_alter_modelusage_call_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsummary',
            name='current',
            field=models.TextField(blank=True),
        ),
    ]
