# Generated by Django 6.0.1 on 2026-04-20 10:54

import django.db.models.deletion
import interact.utils.mediauploadto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0024_sessionsummary_current'),
        ('store', '0013_subtitle_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to=interact.utils.mediauploadto.speaking_audio_upload_to)),
                ('audio_seconds', models.IntegerField(blank=True, default=0)),
                ('transcript', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Speaking Responses',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('lexical_score', models.FloatField(blank=True, null=True)),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interact.speakingresponse')),
            ],
            options={
                'verbose_name_plural': 'Speaking Evaluation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_sessions', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speaking Attempts',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddField(
            model_name='speakingresponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interact.speakingsession'),
        ),
        migrations.CreateModel(
            name='SpeakingRewrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('improved_text', models.TextField()),
                ('band_target', models.DecimalField(decimal_places=1, max_digits=2)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to='interact.speakingresponse')),
            ],
            options={
                'verbose_name_plural': 'Speaking Improvements',
                'ordering': ['band_target'],
                'unique_together': {('response', 'band_target')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='speakingresponse',
            unique_together={('session', 'attempt_number')},
        ),
    ]
