# Generated by Django 6.0.1 on 2026-04-22 06:06

import django.db.models.deletion
import interact.utils.mediauploadto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0025_speakingresponse_speakingevaluation_speakingsession_and_more'),
        ('store', '0013_subtitle_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speakingresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speakingresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='speakingevaluation',
            name='response',
        ),
        migrations.AlterModelOptions(
            name='speakingrewrite',
            options={'verbose_name_plural': 'Speaking Rewrites'},
        ),
        migrations.RenameField(
            model_name='speakingrewrite',
            old_name='improved_text',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='speakingrewrite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='speakingevaluation',
            name='fluency_score',
        ),
        migrations.RemoveField(
            model_name='speakingevaluation',
            name='grammar_score',
        ),
        migrations.RemoveField(
            model_name='speakingevaluation',
            name='lexical_score',
        ),
        migrations.RemoveField(
            model_name='speakingevaluation',
            name='pronunciation_score',
        ),
        migrations.AddField(
            model_name='speakingevaluation',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test', to='store.playlist')),
            ],
            options={
                'verbose_name_plural': 'Mock Tests',
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField()),
                ('audio', models.FileField(upload_to=interact.utils.mediauploadto.speaking_audio_upload_to)),
                ('audio_seconds', models.IntegerField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answers', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Speaking Answers',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='speakingevaluation',
            name='answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interact.speakinganswer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speakingrewrite',
            name='answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rewrite', to='interact.speakinganswer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='interact.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Speaking Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='speakinganswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interact.speakingattempt'),
        ),
        migrations.DeleteModel(
            name='SpeakingSession',
        ),
        migrations.RemoveField(
            model_name='speakingrewrite',
            name='band_target',
        ),
        migrations.RemoveField(
            model_name='speakingrewrite',
            name='response',
        ),
        migrations.AddIndex(
            model_name='speakinganswer',
            index=models.Index(fields=['attempt', 'order'], name='interact_sp_attempt_123da9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakinganswer',
            unique_together={('product', 'attempt')},
        ),
        migrations.DeleteModel(
            name='SpeakingResponse',
        ),
    ]
