# Generated by Django 6.0 on 2026-01-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'AI Companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BasePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Base Prompts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'AI Characters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PersonaPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('role', models.CharField(max_length=255)),
                ('identity', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('communication_style', models.TextField(blank=True)),
                ('behavior', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Persona Prompts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aimodels', to='ai.aicompany')),
            ],
            options={
                'verbose_name_plural': 'AI Models',
                'ordering': ['id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usecase', models.CharField(choices=[('stt', 'STT'), ('tts', 'TTS'), ('chat', 'LLM-Chat'), ('summary', 'LLM-Summary'), ('enhance', 'LLM-Enhance')], default='chat', max_length=32)),
                ('step', models.CharField(choices=[('input', 'Input'), ('cached-input', 'Cached Input'), ('output', 'Output')], default='input', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('unit_amount', models.CharField(choices=[('tokens', '1K Tokens'), ('characters', '1 Character'), ('seconds', '1 Second')], max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelproviders', to='ai.aimodel')),
            ],
            options={
                'verbose_name_plural': 'Model Providers',
                'ordering': ['id'],
                'unique_together': {('model', 'usecase', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('feature', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('voice_id', models.CharField(max_length=255, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.character')),
                ('first_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voices', to='store.language')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='ai.modelprovider')),
            ],
            options={
                'verbose_name_plural': 'Model Voices',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(null=True, upload_to='ai/image/host-back')),
                ('portrait', models.ImageField(null=True, upload_to='ai/image/host-avatar')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('base_prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_profiles', to='ai.baseprompt')),
                ('chat_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_hosts', to='ai.aimodel')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to='store.host')),
                ('stt_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stt_hosts', to='ai.aimodel')),
                ('tts_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tts_hosts', to='ai.aimodel')),
                ('persona_prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_profiles', to='ai.personaprompt')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_profiles', to='ai.voice')),
            ],
            options={
                'verbose_name_plural': 'Host Profiles',
                'ordering': ['created_at'],
            },
        ),
    ]
