# Generated by Django 6.0 on 2026-01-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostprofile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='hostprofile',
            name='portrait',
        ),
    ]
