# Generated by Django 6.0.1 on 2026-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_hostprofile_cover_remove_hostprofile_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='usecase',
            field=models.CharField(choices=[('stt', 'STT'), ('stt-realtime', 'STT-Realtime'), ('tts', 'TTS'), ('tts-stream', 'TTS-Stream'), ('chat', 'LLM-Chat'), ('summary', 'LLM-Summary'), ('enhance', 'LLM-Enhance')], default='chat', max_length=32),
        ),
    ]
