# Generated by Django 6.0.1 on 2026-02-01 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_modelprovider_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='realtime_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='realtime_hosts', to='ai.aimodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='stream_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stream_hosts', to='ai.aimodel'),
            preserve_default=False,
        ),
    ]
